# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  compile:
    docker:
      - image: cimg/base:2021.04
      
    steps:
      - checkout
      - run:
          name: "compile"
          command: "sudo apt update && sudo apt install -y openssh-server screen python git openjdk-8-jdk android-tools-adb bc bison \
                    build-essential curl flex g++-multilib gcc-multilib gnupg gperf imagemagick lib32ncurses-dev \
                    lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev \
                    libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc yasm zip zlib1g-dev \
                    libtinfo5 libncurses5 && bash build.sh"

workflows:
  compile-workflow:
    jobs:
      - compile
